services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    branch: master
    region: oregon
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: YOUR_KEY_HERE
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://your-app.onrender.com
