services:
  - type: web
    name: YemenFleet1
    env: docker
    plan: free
    branch: master
    region: oregon
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths:
        - Dockerfile
        - ./
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://yemenfleet1.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d29dem7gi27c73cf1chg-a.oregon-postgres.render.com
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: yemenfleet_db_po9v
      - key: DB_USERNAME
        value: yemenfleet_db_po9v_user
      - key: DB_PASSWORD
        value: 7A2WmeDBevPkKfYwZnR3mi6ofKE4mZk6
